version: '3.8'

services:
  api:
    container_name: stash_api
    image: node:20.5.1-alpine
    command: yarn start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_DB: stash
      POSTGRES_USER: us3r
      POSTGRES_PASSWORD: p4s5w0rd
    depends_on:
      - db

  db:
    container_name: stash_db
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      DOCKER_DRIVER: overlay
      POSTGRES_DB: stash
      POSTGRES_USER: us3r
      POSTGRES_PASSWORD: p4s5w0rd
