name: Build and test the application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  running-tests:
    runs-on: ubuntu-latest
    container: node:19.5.0-alpine

    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: yarn install

      - name: Run coverage tests
        run: yarn coverage
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
